/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.demo.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class UserEventsKey extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3876548049353201630L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UserEventsKey\",\"namespace\":\"com.demo.avro\",\"fields\":[{\"name\":\"anonymous_id\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<UserEventsKey> ENCODER =
      new BinaryMessageEncoder<UserEventsKey>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<UserEventsKey> DECODER =
      new BinaryMessageDecoder<UserEventsKey>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<UserEventsKey> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<UserEventsKey> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<UserEventsKey>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this UserEventsKey to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a UserEventsKey from a ByteBuffer. */
  public static UserEventsKey fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private int anonymous_id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public UserEventsKey() {}

  /**
   * All-args constructor.
   * @param anonymous_id The new value for anonymous_id
   */
  public UserEventsKey(java.lang.Integer anonymous_id) {
    this.anonymous_id = anonymous_id;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return anonymous_id;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: anonymous_id = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'anonymous_id' field.
   * @return The value of the 'anonymous_id' field.
   */
  public java.lang.Integer getAnonymousId() {
    return anonymous_id;
  }

  /**
   * Sets the value of the 'anonymous_id' field.
   * @param value the value to set.
   */
  public void setAnonymousId(java.lang.Integer value) {
    this.anonymous_id = value;
  }

  /**
   * Creates a new UserEventsKey RecordBuilder.
   * @return A new UserEventsKey RecordBuilder
   */
  public static com.demo.avro.UserEventsKey.Builder newBuilder() {
    return new com.demo.avro.UserEventsKey.Builder();
  }

  /**
   * Creates a new UserEventsKey RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new UserEventsKey RecordBuilder
   */
  public static com.demo.avro.UserEventsKey.Builder newBuilder(com.demo.avro.UserEventsKey.Builder other) {
    return new com.demo.avro.UserEventsKey.Builder(other);
  }

  /**
   * Creates a new UserEventsKey RecordBuilder by copying an existing UserEventsKey instance.
   * @param other The existing instance to copy.
   * @return A new UserEventsKey RecordBuilder
   */
  public static com.demo.avro.UserEventsKey.Builder newBuilder(com.demo.avro.UserEventsKey other) {
    return new com.demo.avro.UserEventsKey.Builder(other);
  }

  /**
   * RecordBuilder for UserEventsKey instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UserEventsKey>
    implements org.apache.avro.data.RecordBuilder<UserEventsKey> {

    private int anonymous_id;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.demo.avro.UserEventsKey.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.anonymous_id)) {
        this.anonymous_id = data().deepCopy(fields()[0].schema(), other.anonymous_id);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing UserEventsKey instance
     * @param other The existing instance to copy.
     */
    private Builder(com.demo.avro.UserEventsKey other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.anonymous_id)) {
        this.anonymous_id = data().deepCopy(fields()[0].schema(), other.anonymous_id);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'anonymous_id' field.
      * @return The value.
      */
    public java.lang.Integer getAnonymousId() {
      return anonymous_id;
    }

    /**
      * Sets the value of the 'anonymous_id' field.
      * @param value The value of 'anonymous_id'.
      * @return This builder.
      */
    public com.demo.avro.UserEventsKey.Builder setAnonymousId(int value) {
      validate(fields()[0], value);
      this.anonymous_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'anonymous_id' field has been set.
      * @return True if the 'anonymous_id' field has been set, false otherwise.
      */
    public boolean hasAnonymousId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'anonymous_id' field.
      * @return This builder.
      */
    public com.demo.avro.UserEventsKey.Builder clearAnonymousId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public UserEventsKey build() {
      try {
        UserEventsKey record = new UserEventsKey();
        record.anonymous_id = fieldSetFlags()[0] ? this.anonymous_id : (java.lang.Integer) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<UserEventsKey>
    WRITER$ = (org.apache.avro.io.DatumWriter<UserEventsKey>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<UserEventsKey>
    READER$ = (org.apache.avro.io.DatumReader<UserEventsKey>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
